<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button login</name>
   <tag></tag>
   <elementGuidId>07fcf716-bad9-43d6-b545-6f78100d4099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnsubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f75c179-7a94-46ab-b8b2-c3358ff83ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6356a59a-fff5-4e09-929a-b6ffbd166cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>b66d31d9-f222-4205-98c7-9cf128029f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>8d79e548-7a01-4e5c-bd8f-74d1db14334e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>c88f4cac-e549-4ac2-a73d-d0c9eca88241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-md</value>
      <webElementGuid>a78fe9fa-2c66-4825-bad0-2a8408940aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsubmit&quot;)</value>
      <webElementGuid>1762044d-f16e-417c-bb9a-ae56829f336d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnsubmit']</value>
      <webElementGuid>501fc82b-8371-4cf6-8b9d-f1a629e5d4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/div/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>80974d50-6f60-44be-87cc-79bed522739d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>bff24df5-8b37-48c1-87cf-d02d41b4e6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnsubmit' and @id = 'btnsubmit']</value>
      <webElementGuid>18c22a47-eee5-40a0-b1d8-5861305ca433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
