<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Antrian</name>
   <tag></tag>
   <elementGuidId>dba4b0bc-7ceb-4481-914a-0fadc1e94582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb55d5b8-a1dc-4481-8d98-9059bd687c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>9a577a99-43a1-4aef-b1f6-851d5e5557a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>DaftarAntrian.aspx</value>
      <webElementGuid>93678e55-1959-4342-b1f2-3579c49bf6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t0</value>
      <webElementGuid>2b566037-d3ed-428b-ba8a-f0311acb04c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Antrian</value>
      <webElementGuid>b1c6dc4b-3a56-40dc-abd4-4ec26a3df097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t0&quot;)</value>
      <webElementGuid>cb6525cd-19e4-401c-975a-823bbe738df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t0']</value>
      <webElementGuid>92a7ab72-5323-437f-bca1-47034d6a9630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>9c6c2776-287a-446e-9139-c6542e53a3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar Antrian')]</value>
      <webElementGuid>3494e184-b501-401e-b88c-521eb7caf3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Navigation Links.'])[1]/following::a[1]</value>
      <webElementGuid>8ec40281-7d37-4989-aeeb-ba458704f979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Penanganan'])[1]/preceding::a[1]</value>
      <webElementGuid>32620506-21ed-4cd0-8aa9-a2c354d085a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Penanganan'])[1]/preceding::a[3]</value>
      <webElementGuid>a72e31eb-ebde-47ed-b789-8af920b27a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Antrian']/parent::*</value>
      <webElementGuid>5e45efe1-a475-481a-a1b2-0632cb361976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'DaftarAntrian.aspx')]</value>
      <webElementGuid>6bd884ae-269d-4385-a0f2-4297a73cdb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>3887ddf4-face-4478-9d56-9a81ca507777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'DaftarAntrian.aspx' and @id = 'TreeView1t0' and (text() = 'Daftar Antrian' or . = 'Daftar Antrian')]</value>
      <webElementGuid>4d630d3b-a48e-4cfc-a98d-b52162d9c06c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
