<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Browse</name>
   <tag></tag>
   <elementGuidId>b44de74c-6dfc-4118-a17f-0b7aeaacfb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_FileUpload1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_FileUpload1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2dda8ff-a8f8-47ef-8dfb-29bdf12e2454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2ed25db9-17a9-4d66-8ad0-54bd4ceff626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$FileUpload1</value>
      <webElementGuid>d7533d19-07cb-4c83-8f4e-5d96d3977f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_FileUpload1</value>
      <webElementGuid>e7486899-4225-462f-805a-971e42c4df2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fd194920-90e1-45ee-9f38-5945eb4b69d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_FileUpload1&quot;)</value>
      <webElementGuid>b3b467ad-9acc-49d4-ac9c-25a16c9d3a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_FileUpload1']</value>
      <webElementGuid>32c8c332-3609-4af9-89a4-5c2ae3de6dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div/div[2]/div[13]/div/input</value>
      <webElementGuid>28ba3091-13e4-43b7-9fef-d18d84ab1fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>de7e974b-c70f-4a1f-b519-1369aee8b9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$main$FileUpload1' and @id = 'main_FileUpload1']</value>
      <webElementGuid>cc4264b0-7094-4f73-88e9-e8a1bc94edf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
